from typing import ContextManager, Protocol

from dtcoder_agentic_dev.domain.events import DomainEvent
from dtcoder_agentic_dev.domain.models import (
    Artifact,
    ExternalOperation,
    Issue,
    StepAttempt,
    WorkflowRun,
)


class RunRepository(Protocol):
    def transaction(self) -> ContextManager[None]: ...
    def save_repository(self, repository_id: str, data: dict) -> None: ...
    def save_issue(self, issue: Issue) -> None: ...
    def load_issue(self, repository_id: str, external_id: str) -> Issue: ...
    def create_run(self, run: WorkflowRun) -> None: ...
    def load_run(self, run_id: str) -> WorkflowRun: ...
    def update_run(self, run: WorkflowRun) -> None: ...
    def list_runs(self, repository_id: str | None = None) -> list[WorkflowRun]: ...
    def claim_run(
        self, owner: str, now: float, lease_seconds: float, run_id: str | None = None
    ) -> WorkflowRun | None: ...
    def renew_lease(self, run_id: str, owner: str, now: float, lease_seconds: float) -> None: ...
    def release_lease(self, run_id: str, owner: str) -> None: ...
    def assert_lease(self, run_id: str, owner: str, now: float) -> None: ...
    def save_attempt(self, attempt: StepAttempt) -> None: ...
    def list_attempts(self, run_id: str) -> list[StepAttempt]: ...
    def save_artifact(self, artifact: Artifact) -> None: ...
    def list_artifacts(self, run_id: str) -> list[Artifact]: ...
    def save_operation(self, operation: ExternalOperation) -> None: ...
    def find_operation(self, idempotency_key: str) -> ExternalOperation | None: ...
    def list_operations(self, run_id: str) -> list[ExternalOperation]: ...
    def save_event(self, event: DomainEvent) -> None: ...
    def list_events(self, run_id: str) -> list[DomainEvent]: ...
