from typing import Protocol


class WorkflowDefinitions(Protocol):
    def save(self, run_id: str, original: str, resolved: str) -> dict: ...
    def read(self, run_id: str, reference: dict) -> tuple[str, str]: ...
    def read_skill(self, relative_path: str) -> str: ...
