from typing import Protocol

from dtcoder_agentic_dev.domain.models import WorkflowRun


class WorkspaceManager(Protocol):
    def prepare(self, run: WorkflowRun, repository: object) -> str: ...
    def recover(self, run: WorkflowRun, repository: object) -> str: ...
    def cleanup(self, run: WorkflowRun) -> None: ...
    def prepare_at(self, run: WorkflowRun, repository: object, revision: str) -> str: ...


class GitPort(Protocol):
    def is_repository(self, path: str) -> bool: ...
    def current_branch(self, path: str) -> str: ...
    def head_sha(self, path: str) -> str: ...
    def status_porcelain(self, path: str) -> str: ...
    def snapshot_untracked(self, path: str) -> set[str]: ...
    def diff_name_only(self, path: str, base: str) -> list[str]: ...
    def commit_changes(
        self, path: str, message: str, *, artifact_paths: list[str], untracked_before: set[str]
    ) -> bool: ...
    def push(self, path: str, branch: str) -> None: ...

    def backup_ref(self, path: str, reference: str, revision: str) -> None: ...
    def is_ancestor(self, path: str, revision: str) -> bool: ...
